<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class CitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
         $cities = [
         'Alaminos',
         'Alangalang',
         'Angat',
         'Angeles City',
         'Antipolo City',
         'Bacolod',
         'Bacoor City',
         'Bago',
         'Baguio',
         'Bais',
         'Balanga City',
         'Balayan',
         'Batangas City',
         'Bayawan',
         'Binan City',
         'Bislig',
         'Butuan',
         'Cabanatuan',
         'Cabuyao',
         'Cadiz',
         'Cagayan de Oro',
         'Cainta',
         'Calamba City',
         'Calapan',
         'Calbayog',
         'Caloocan City',
         'Candon',
         'Canlaon',
         'Cauayan',
         'Cavite City',
         'Cebu City',
         'Cotabato City',
         'Dagupan',
         'Danao',
         'Dapitan',
         'Dasmarinas',
         'Davao City',
         'Digos City',
         'Dipolog',
         'Dumaguete',
         'Escalante City',
         'Gapan',
         ' General Santos',
         'Gingoog',
         'Guimba',
         'Himamaylan',
         'Iligan',
         'Iloilo City',
         'Imus City',
         'Iriga',
         'Isabela',
         'Kabankalan',
         'Kidapawan',
         'Koronadal',
         'La Carlota',
         'Laoag',
         'Lapu-Lapu City',
         'Las Pinas',
         'Legazpi City',
         'Ligao',
         'Lipa',
         'Lucena City',
         'Maasin',
         'Mabalacat City',
         'Makati City',
         'Malabon',
         'Malay',
         'Malaybalay City',
         'Malolos',
         ' Mandaluyong City',
         'Mandaue,
         Manila',
         'Marawi',
         'Marikina',
         'Masbate City',
         'Meycauayan',
         'Munoz',
         'Muntinlupa City',
         'Naga',
         'Navotas',
         'New Lucena',
         'Olongapo City',
         'Ormoc',
         'Oroquieta',
         'Ozamiz City',
         'Pagadian',
         'Palayan',
         'Panabo',
         'Paranaque City',
         'Pasay City',
         'Pasig City',
         'Passi',
         'Pateros',
         'Puerto Galera',
         'Puerto Princesa',
         'Quezon City',
         'Roxas City',
         'Sagay',
         'Samal',
         ' San Carlos City',
         'San Fernando',
         'San Ildefonso',
         'San Jose',
         'San Jose del Monte',
         'San Juan',
         'San Pablo City',
         'San Pedro',
         ' Santa Rosa City',
         'Santiago',
         'Silay',
         'Sipalay City',
         'Sorsogon City',
         'Subic Bay Freeport Zone',
         'Surigao City',
         'Tabaco',
         'Tacloban',
         'Tacurong',
         'Tagaytay',
         'Tagbilaran',
         'Taguig City',
         'Tagum',
         ' Talisay City',
         'Tanauan',
         'Tangub City',
         'Tanjay',
         'Tanza',
         'Tarlac City',
         'Toledo',
         'Trece Martires',
         'Tuguegarao City',
         'Urdaneta',
         'Valencia',
         'Valenzuela',
         'Victorias',
         'Vigan',
         'Zamboanga City'
         ];

         foreach($cities as $city){
         \App\Models\City::factory()->create([
         'province_id' => rand(1,80),
         'city' => $city
         ]);
         }
    }
}
