<!DOCTYPE html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <!-- Favicon -->
    <link rel="icon" href="{{ storage_path('/brands/favicon.ico') }}" type="image/png">

    <title>{{ config('app.name', 'The Property Manager') }} @yield('title')</title>

    <!-- Fonts -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap">

    <link rel="stylesheet" href="https://unpkg.com/flowbite@1.3.4/dist/flowbite.min.css" />

    {{-- Fontawesome --}}
    <script src="https://kit.fontawesome.com/b3c8174312.js" crossorigin="anonymous"></script>

    <!-- Styles -->
    <link rel="stylesheet" href="{{ storage_path('css/app.css') }}">

    <!-- Scripts -->
    <script src="{{ storage_path('js/app.js') }}" defer></script>

    {{-- Alpine.js --}}
    <script defer src="https://unpkg.com/alpinejs@3.2.4/dist/cdn.min.js"></script>

    {{-- Flowbite --}}
    <script src="../path/to/flowbite/dist/flowbite.js"></script>

    @yield('styles')

    @livewireStyles
</head>

<body>
    <p class="text-left">{{ Session::get('property_name') }}</p>
    <div class="text-sm">
        <p class="text-center">Contract Information</p>
        <br>
        <p>Tenant: {{ $tenant }}</p>
        <p>Unit: {{ $unit }}</p>
        <p>Duration: {{ Carbon\Carbon::parse($start)->format('M d, Y').' -
            '.Carbon\Carbon::parse($end)->format('M d, Y') }}</p>
        <p>Rent/month: {{
            number_format($rent, 2) }}</p>
        <p>Discount: {{number_format($discount, 2) }}</p>
        <p>Status: {{ $status }}</p>
        <p>Interaction: {{ $interaction }}</p>
        <p>Reason for moving out: {{ $moveout_reason }}</p>
        <p>Assisted by: {{ $user }}</p>
        <br>
        <hr>    
        <br>
        <p class="text-center">Move-in charges</p>
        <br>
        @foreach ($reference_no as $reference_no)
        <p>Referece No: {{ $reference_no->reference_no }}</p>
        @endforeach
        <?php $ctr=1; ?>
        <table class="table-auto">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Bill No</th>
                    <th>Particular</th>
                    <th>Period Covered</th>
                    <th>Amount</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($bills as $bill)

                <tr>
                    <td>{{ $ctr++ }}</td>
                    <td>{{ $bill->bill_no }}</td>
                    <td>{{ $bill->particular }}</td>
                    <td>
                        {{ Carbon\Carbon::parse($bill->start)->format('M d, Y').' -
                        '.Carbon\Carbon::parse($bill->end)->format('M d, Y') }}
                    </td>
                    <td>{{ number_format($bill->bill, 2) }}</td>
                </tr>

                @endforeach
                <tr>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td>{{ number_format($bills->sum('bill'), 2) }}</td>
                </tr>
            </tbody>
        </table>
        <br>
        <hr>
        <h6 class="text-center">Generated by the ThePMO Co.</h6>
    </div>
</body>

<script src="https://unpkg.com/flowbite@1.3.4/dist/flowbite.js"></script>

@yield('scripts')

</html>